/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: res16                                                 *
* Dimensions:  20 * 20                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmres16;

static GUI_CONST_STORAGE unsigned char _acres16[] = {
  /* RLE: 038 Pixels @ 000,000 */ 38, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 018,001 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 019 Pixels @ 019,001 */ 19, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 018,002 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 019 Pixels @ 019,002 */ 19, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 018,003 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 019 Pixels @ 019,003 */ 19, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 018,004 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 019 Pixels @ 019,004 */ 19, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 018,005 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 019 Pixels @ 019,005 */ 19, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 018,006 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 018 Pixels @ 019,006 */ 18, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 017,007 */ 0, 2, 0x95, 0xFF, 0x28, 0x00, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 005 Pixels @ 019,007 */ 5, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 004,008 */ 7, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 006 Pixels @ 011,008 */ 6, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 017,008 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 006 Pixels @ 018,008 */ 6, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 004,009 */ 7, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 011,009 */ 1, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 005 Pixels @ 012,009 */ 5, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* ABS: 004 Pixels @ 017,009 */ 0, 4, 0x94, 0xFF, 0x28, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 011 Pixels @ 001,010 */ 11, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 012,010 */ 1, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 004 Pixels @ 013,010 */ 4, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 017,010 */ 1, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 006 Pixels @ 018,010 */ 6, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 004,011 */ 9, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 003 Pixels @ 013,011 */ 3, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 016,011 */ 0, 2, 0x96, 0xFE, 0x28, 0x00, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 006 Pixels @ 018,011 */ 6, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 012 Pixels @ 004,012 */ 12, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 016,012 */ 1, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 007 Pixels @ 017,012 */ 7, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 004,013 */ 11, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 015,013 */ 1, 0x95, 0xFF, 0x28, 0x00, 
  /* RLE: 008 Pixels @ 016,013 */ 8, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 004,014 */ 9, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 013,014 */ 1, 0x9B, 0xFA, 0x26, 0x00, 
  /* RLE: 010 Pixels @ 014,014 */ 10, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 004,015 */ 9, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 007 Pixels @ 013,015 */ 7, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 001 Pixels @ 000,016 */ 1, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 011 Pixels @ 001,016 */ 11, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 012,016 */ 1, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 011 Pixels @ 013,016 */ 11, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 004,017 */ 7, 0x94, 0xFF, 0x28, 0x00, 
  /* RLE: 001 Pixels @ 011,017 */ 1, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 012 Pixels @ 012,017 */ 12, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 004,018 */ 7, 0x96, 0xFE, 0x28, 0x00, 
  /* RLE: 029 Pixels @ 011,018 */ 29, 0xFF, 0xFF, 0xFF, 0xFF, 
  0
};  // 280 for 400 pixels

GUI_CONST_STORAGE GUI_BITMAP bmres16 = {
  20, // xSize
  20, // ySize
  80, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acres16,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE32
};

/*************************** End of file ****************************/
