/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: res32                                                 *
* Dimensions:  20 * 20                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmres32;

static GUI_CONST_STORAGE unsigned char _acres32[] = {
  /* RLE: 068 Pixels @ 000,000 */ 68, 0xFF, 
  /* ABS: 004 Pixels @ 008,003 */ 0, 4, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 012 Pixels @ 012,003 */ 12, 0xFF, 
  /* ABS: 012 Pixels @ 004,004 */ 0, 12, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 009 Pixels @ 016,004 */ 9, 0xFF, 
  /* ABS: 010 Pixels @ 005,005 */ 0, 10, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 011 Pixels @ 015,005 */ 11, 0xFF, 
  /* ABS: 002 Pixels @ 006,006 */ 0, 2, 0x00, 0xFF, 
  /* RLE: 004 Pixels @ 008,006 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 012,006 */ 0, 2, 0xFF, 0x00, 
  /* RLE: 013 Pixels @ 014,006 */ 13, 0xFF, 
  /* RLE: 006 Pixels @ 007,007 */ 6, 0x00, 
  /* RLE: 010 Pixels @ 013,007 */ 10, 0xFF, 
  /* RLE: 014 Pixels @ 003,008 */ 14, 0x00, 
  /* RLE: 009 Pixels @ 017,008 */ 9, 0xFF, 
  /* RLE: 008 Pixels @ 006,009 */ 8, 0x00, 
  /* RLE: 012 Pixels @ 014,009 */ 12, 0xFF, 
  /* RLE: 008 Pixels @ 006,010 */ 8, 0x00, 
  /* RLE: 009 Pixels @ 014,010 */ 9, 0xFF, 
  /* RLE: 014 Pixels @ 003,011 */ 14, 0x00, 
  /* RLE: 010 Pixels @ 017,011 */ 10, 0xFF, 
  /* RLE: 006 Pixels @ 007,012 */ 6, 0x00, 
  /* RLE: 013 Pixels @ 013,012 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 006,013 */ 0, 2, 0x00, 0xFF, 
  /* RLE: 004 Pixels @ 008,013 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 012,013 */ 0, 2, 0xFF, 0x00, 
  /* RLE: 011 Pixels @ 014,013 */ 11, 0xFF, 
  /* ABS: 010 Pixels @ 005,014 */ 0, 10, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 009 Pixels @ 015,014 */ 9, 0xFF, 
  /* ABS: 012 Pixels @ 004,015 */ 0, 12, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 
  /* RLE: 012 Pixels @ 016,015 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 008,016 */ 0, 4, 0x00, 0xFF, 0xFF, 0x00, 
  /* RLE: 068 Pixels @ 012,016 */ 68, 0xFF, 
  0
};  // 126 bytes for 400 pixels

GUI_CONST_STORAGE GUI_BITMAP bmres32 = {
  20, // xSize
  20, // ySize
  20, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acres32,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
